---
title: "US Ski Resort Analysis"
author: "Tristan Hamilton"
date: "2024-02-19"
categories: [Blog Post 2]
#image: 
---


```{r include=FALSE} 
library(tidyverse)
library(maps)
library(here)
library(tools)
library(broom)
library(knitr)
# install.packages("modelr")
library(modelr)
us_ski <- read_csv(here("data/ski_resorts.csv"))
```

## <https://gist.github.com/Ewiseman/b251e5eaf70ca52a4b9b10dce9e635a4>

### Part 1: Ski Resorts per State
```{r message=FALSE}
us_ski <- us_ski |> separate(resort_name,
                             sep = ",",
                             into = c("resort", "state_abbr"))

num_state <- us_ski |> group_by(state) |>
  summarise(num_resort = n()) 

state_df <- ggplot2::map_data("state")
state_df$region <- toTitleCase(state_df$region)

resort_map <- left_join(state_df, num_state, by = c("region" = "state"))
```

```{r}
ggplot(data = resort_map, mapping = aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = num_resort), color = "black") +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  scale_fill_viridis_c(name = "Number of Resorts") +
  labs(title = "Ski Resorts per State") +
  theme_void() 
```

```{r}
numres_df <- us_ski |>
  group_by(state) |>
  summarise(num_resorts = n()) |>
  arrange(desc(num_resorts)) |>
  slice(1:6)

kable(numres_df,
      caption = "Top 6 States: Number of SKi Resorts",
      col.names = c("State", "Number of Resorts"))
```

### Part 2: Difficulty

```{r message=FALSE}
difficulty_df <- us_ski |>
  arrange(desc(black_percent)) |>
  slice(1:10) 

difficulty_df <- difficulty_df |>
  pivot_longer(cols = c(green_percent, blue_percent, black_percent),
               names_to = "difficulty",
               values_to = "percent") |>
  mutate(percent = ifelse(is.na(percent), 0, percent))

ggplot(data = difficulty_df, aes(x = resort, y = percent, fill = difficulty)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = c("green_percent" = "green4",
                    "blue_percent" = "blue2",
                    "black_percent" = "black"), name = "Difficulty Level") +
  theme_minimal() +
  labs(title = "Top 10 Most Difficult Ski Resorts",
       y = "Percent Black Diamond",
       x = "Ski Resort Name")
```
Takeaway:

```{r}
ggplot(data = us_ski, aes(x = summit, y = vertical)) +
  geom_point(size = 0.9) +
  geom_smooth(color = "blue4") +
  theme_minimal() +
  labs(title = "Relationship between Vertical Drop and Summit Elevation",
       x = "Summit Elevation (ft)",
       y = "Vertical Drop (ft)")
```

```{r}
vert_df <- us_ski |>
  group_by(resort) |>
  summarise(total_vert = sum(vertical)) |>
  arrange(desc(total_vert)) |>
  slice(1:15)

kable(vert_df,
      caption = "Top 15 Ski Resorts: Vertical Drop",
      col.names = c("Ski Resort", "Vertical Drop (ft)"))
```

