{
  "hash": "e813b97ceae0ab232dc0561ca673016e",
  "result": {
    "markdown": "---\ntitle: \"US Ski Resort Analysis\"\nauthor: \"Tristan Hamilton\"\ndate: \"2024-02-19\"\ncategories: [Blog Post 2]\n#image: \n---\n\n\n\n\n### Introduction:\nI chose a data set from 2017 with data on US ski resorts. There are 364 observations and 16 variables ranging from vertical drop, elevation (base and summit), lifts, runs, acres, and more. I will be looking into difficulty level, that is, which ski resorts have the highest percentage of black-diamond trails. I will also investigate vertical drop, and the states with the most ski resorts. The data set can be found at <https://gist.github.com/Ewiseman/b251e5eaf70ca52a4b9b10dce9e635a4> and we can also glance at it below:\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(us_ski))\n```\n\n::: {.cell-output-display}\n|resort_name           |state        | summit| base| vertical| lifts| runs| acres| green_percent| green_acres| blue_percent| blue_acres| black_percent| black_acres|   lat|     lon|\n|:---------------------|:------------|------:|----:|--------:|-----:|----:|-----:|-------------:|-----------:|------------:|----------:|-------------:|-----------:|-----:|-------:|\n|49(degrees) North, WA |Washington   |   5774| 3923|     1851|     6|   68|  2325|          0.30|      697.50|         0.40|     930.00|          0.30|      697.50| 49.00| -115.84|\n|Afton Alps, MN        |Minnesota    |    700|  350|      350|    21|   48|   300|          0.20|       60.00|         0.60|     180.00|          0.20|       60.00| 44.85|  -92.79|\n|Alpine Meadows, CA    |California   |   8673| 6385|     2288|    13|  100|  2400|          0.25|      600.00|         0.40|     960.00|          0.35|      840.00| 39.17| -120.22|\n|Alpine Mountain, PA   |Pennsylvania |   1150|  600|      500|     3|   21|   120|          0.17|       20.40|         0.55|      66.00|          0.28|       33.60| 40.08|  -76.90|\n|Alpine Valley, MI     |Michigan     |   1210|  910|      300|    14|   25|   118|          0.39|       46.02|         0.26|      30.68|          0.35|       41.30| 44.96|  -84.87|\n|Alpine Valley, OH     |Ohio         |   1500| 1260|      230|     6|   11|    72|          0.33|       23.76|         0.34|      24.48|          0.33|       23.76| 40.31|  -83.68|\n:::\n:::\n\n\n\n### Part 1: Number of Ski Resorts per State\n\n::: {.cell}\n\n```{.r .cell-code}\nus_ski <- us_ski |> separate(resort_name,\n                             sep = \",\",\n                             into = c(\"resort\", \"state_abbr\"))\n\nnum_state <- us_ski |> group_by(state) |>\n  summarise(num_resort = n()) \n\nstate_df <- ggplot2::map_data(\"state\")\nstate_df$region <- toTitleCase(state_df$region)\n\nresort_map <- left_join(state_df, num_state, by = c(\"region\" = \"state\"))\n\nggplot(data = resort_map, mapping = aes(x = long, y = lat, group = group)) +\n  geom_polygon(aes(fill = num_resort), color = \"black\") +\n  coord_map(projection = \"albers\", lat0 = 39, lat1 = 45) +\n  scale_fill_viridis_c(name = \"Number of Resorts\") +\n  labs(title = \"Ski Resorts per State\") +\n  theme_void() \n```\n\n::: {.cell-output-display}\n![](ski_resort_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\nThe above map shows the number of ski resorts per state. Some states are gray, indicating there are no ski resorts. The sequential color scale allows us to see the states with higher numbers of ski resorts. New York, Michigan, Colorado, and Pennsylvania stand out as the states with the most ski resorts. Despite having access to skiing in many states, the number of resorts varies, and the size of the resorts varies as well. Even though Pennsylvania has a lot of ski resorts, on average they're significantly smaller than ski resorts in a state like Colorado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnumres_df <- us_ski |>\n  group_by(state) |>\n  summarise(num_resorts = n()) |>\n  arrange(desc(num_resorts)) |>\n  slice(1:6)\n\nkable(numres_df,\n      caption = \"Top 6 States: Number of SKi Resorts\",\n      col.names = c(\"State\", \"Number of Resorts\"))\n```\n\n::: {.cell-output-display}\nTable: Top 6 States: Number of SKi Resorts\n\n|State        | Number of Resorts|\n|:------------|-----------------:|\n|New York     |                34|\n|Michigan     |                32|\n|Colorado     |                24|\n|Pennsylvania |                23|\n|Wisconsin    |                22|\n|California   |                18|\n:::\n:::\n\nThe above table summarizes the top 6 states with the most ski resorts. The top 3 states are New York (34), Michigan (32), and Colorado (24). \n\n### Part 2: Which Ski Resorts are the Most Difficult?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndifficulty_df <- us_ski |>\n  arrange(desc(black_percent)) |>\n  slice(1:10) \n\ndifficulty_df <- difficulty_df |>\n  pivot_longer(cols = c(green_percent, blue_percent, black_percent),\n               names_to = \"difficulty\",\n               values_to = \"percent\") |>\n  mutate(percent = ifelse(is.na(percent), 0, percent))\n\nggplot(data = difficulty_df, aes(x = resort, y = percent, fill = difficulty)) +\n  geom_bar(stat = \"identity\") +\n  coord_flip() +\n  scale_fill_manual(values = c(\"green_percent\" = \"green4\",\n                    \"blue_percent\" = \"blue2\",\n                    \"black_percent\" = \"black\"), name = \"Difficulty Level\") +\n  theme_minimal() +\n  labs(title = \"Top 10 Most Difficult Ski Resorts\",\n       y = \"Percent Black Diamond\",\n       x = \"Ski Resort Name\")\n```\n\n::: {.cell-output-display}\n![](ski_resort_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nThe above graph shows the most difficult ski resorts in the US based on the variable percent black. Since every ski trail has a rating: green (easy), blue (intermediate), and black (expert), we can look at the ski resorts with highest percentage of black diamond trails. In this case, Silverton (Colorado) is 100% black diamond, followed by Mount Bohemia (Michigan) at 93%, and Mt. Ashland (Oregon) at 75%. The rest of the top 10 has about 50% black diamond trails. We do have to consider that there is not a \"baseline\" scale in rating a trail's difficulty, so there is likely some level of inaccuracy here. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = us_ski, aes(x = summit, y = vertical)) +\n  geom_point(size = 0.9) +\n  geom_smooth(color = \"blue4\") +\n  theme_minimal() +\n  labs(title = \"Relationship between Vertical Drop and Summit Elevation\",\n       x = \"Summit Elevation (ft)\",\n       y = \"Vertical Drop (ft)\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 30 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 30 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](ski_resort_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nThe above graph show the relationship between vertical drop and summit elevation of a ski resort. There is not constant variance; however, the smoothed line shows the overall trend. We can see that the ski resorts with higher summit elevation are more likely to have more vertical drop. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nvert_df <- us_ski |>\n  group_by(resort) |>\n  summarise(total_vert = sum(vertical)) |>\n  arrange(desc(total_vert)) |>\n  slice(1:15)\n\nkable(vert_df,\n      caption = \"Top 15 Ski Resorts: Vertical Drop\",\n      col.names = c(\"Ski Resort\", \"Vertical Drop (ft)\"))\n```\n\n::: {.cell-output-display}\nTable: Top 15 Ski Resorts: Vertical Drop\n\n|Ski Resort         | Vertical Drop (ft)|\n|:------------------|------------------:|\n|Telluride          |               4570|\n|Snowmass           |               4406|\n|Big Sky            |               4350|\n|Jackson Hole       |               4139|\n|Timberline         |               3690|\n|Steamboat          |               3668|\n|Aspen Highlands    |               3635|\n|Heavenly           |               3527|\n|Crystal Mountain   |               3475|\n|Vail               |               3450|\n|Whiteface Mountain |               3430|\n|Snowbird           |               3400|\n|Sun Valley         |               3400|\n|Breckenridge       |               3398|\n|Mt. Bachelor       |               3365|\n:::\n:::\n\nThe above table shows the top 15 ski resorts with the most vertical drop. Telluride (Colorado) has the most vertical at 4570 feet, followed by Snowmass (Colorado) at 4406 feet, and Big Sky (Montana) at 4350 feet. In the top 15, only one mountain is on the East Coast, Whiteface Mountain, with 3430 feet of vertical drop. \n\n### Conclusion: \nAlthough this data set is pretty extensive, it doesn't include every ski resort in the country Other limitations include rating trail difficulty. There isn't a \"baseline\" scale used to rate difficulty, so a black trail at a mountain in Michigan may be a blue in Colorado. I've been using the word \"ski resort\" to be consistent with the data set, so in this analysis the term \"ski resort\" is interchangeable with \"ski area\". However, resorts are typically more comprehensive, developed, and are operated by large corporations. Contrarily, a ski area is more likely to be independent or community-operated with less amenities and fairer prices. In further analysis, I'd be interesting in a variable that specifies the ownership of the mountain (corporation vs. independent), and other categorical variables like region (east coast vs west coast). \n\n### Connection to Class: \nWhen looking at the number of ski resorts in each state, a map is an effective visualization. It makes it easy to see which states don't have ski resorts, which have the most, and perhaps comparing states in certain regions. I included a table with this data as well just to see more exact numbers. \n",
    "supporting": [
      "ski_resort_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}