{
  "hash": "480decb8d27c5ccfa017bea75e99baf2",
  "result": {
    "markdown": "---\ntitle: \"Global Alcohol Consumption\"\nauthor: \"Tristan Hamilton\"\ndate: \"2024-02-8\"\ncategories: [Blog Post 1]\n---\n\n\n\n\n### Introduction:\nI am curious how alcohol consumption varies globally and which types of alcohol are more prevalent in certain countries. I chose a data set from 2018 on global alcohol consumption with 193 observations of 5 variables. In addition to a 'country' variable, there are variables corresponding to annual servings (per capita) of beer, wine, spirits, and pure alcohol. First, I will look into the total alcohol consumption for each country, and visualize this on a world map. Next, I'll investigate the top-consuming countries of the different types of alcohol. The data set can be found here: <https://github.com/rfordatascience/tidytuesday/blob/master/data/2018/2018-06-26/week13_alcohol_global.csv>.\n\n### Part 1:\n\n::: {.cell}\n\n```{.r .cell-code}\nworld_df <- ggplot2::map_data(\"world\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_alc <- global_alc |> mutate(country = fct_recode(country, \n                                                        \"Russia\" = \"Russian Federation\",\n                                                        \"UK\" = \"United Kingdom\",\n                                                        \"Democratic Republic of the Congo\" = \"DR Congo\",\n                                                        \"Ivory Coast\" = \"Cote d'Ivoire\"))\nworld_alc <- left_join(world_df, global_alc, by = c(\"region\" = \"country\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nworld_alc <- world_alc |> \n  mutate(total_consumption = beer_servings + wine_servings + spirit_servings)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = world_alc, aes(x = long, y = lat, group = group)) +\n  geom_polygon(aes(fill = total_consumption), color = \"black\", linewidth = 0.1) +\n  coord_map(projection = \"mercator\", xlim = c(-180, 180)) +\n  scale_fill_viridis_c(name = \"Alcohol (servings)\") +\n  labs(title = \"Global Alcohol Consumption by Country\",\n       x = \"Longitude\",\n       y = \"Latitude\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nThis visualization shows global alcohol consumption by country. The variable 'total_consumption' accounts for the sum of each country's beer, wine, and spirit consumption. With a sequential color scale, we are easily able to see the different levels of alcohol consumption. According to the visualization, Russia and several European countries consume the most alcohol, while the Middle East and Africa consume the least amount. \n\n### Part 2:\n\n### The Top 5 Consuming Countries of Wine, Beer, Spirits, and Pure Alcohol:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwine_df <- global_alc |>\n  group_by(country) |>\n  arrange(desc(wine_servings)) |>\n  select(country, wine_servings) |>\n  head(5)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_df <- global_alc |>\n  group_by(country) |>\n  arrange(desc(beer_servings)) |>\n  select(country, beer_servings) |>\n  head(5)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nspirit_df <- global_alc |>\n  group_by(country) |>\n  arrange(desc(spirit_servings)) |>\n  select(country, spirit_servings) |>\n  head(5)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npurealc_df <- global_alc |>\n  group_by(country) |>\n  arrange(desc(total_litres_of_pure_alcohol)) |>\n  select(country, total_litres_of_pure_alcohol) |>\n  head(5)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(wine_df,\n      caption = \"Top 5 Countries: Wine Consumption\",\n      col.names = c(\"Country\", \"Wine Servings\"))\n```\n\n::: {.cell-output-display}\nTable: Top 5 Countries: Wine Consumption\n\n|Country     | Wine Servings|\n|:-----------|-------------:|\n|France      |           370|\n|Portugal    |           339|\n|Andorra     |           312|\n|Switzerland |           280|\n|Denmark     |           278|\n:::\n:::\n\nThe above table shows the top 5 wine-consuming countries based on annual servings. France is the top consumer with 370 servings per year (per capita). All of these countries are located in Western Europe, which is not surprising given this region's reputation for high quality wine. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(beer_df,\n      caption = \"Top 5 Countries: Beer Consumption\",\n      col.names = c(\"Country\", \"Beer Servings\"))\n```\n\n::: {.cell-output-display}\nTable: Top 5 Countries: Beer Consumption\n\n|Country        | Beer Servings|\n|:--------------|-------------:|\n|Namibia        |           376|\n|Czech Republic |           361|\n|Gabon          |           347|\n|Germany        |           346|\n|Lithuania      |           343|\n:::\n:::\n\nThe above table shows the top 5 beer-consuming countries based on annual servings. Namibia is the top consumer with 376 servings per year (per capita). There are also several European countries in the top 5, including Germany.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(spirit_df,\n      caption = \"Top 5 Countries: Spirit Consumption\",\n      col.names = c(\"Country\", \"Spirit Servings\"))\n```\n\n::: {.cell-output-display}\nTable: Top 5 Countries: Spirit Consumption\n\n|Country   | Spirit Servings|\n|:---------|---------------:|\n|Grenada   |             438|\n|Belarus   |             373|\n|Haiti     |             326|\n|Russia    |             326|\n|St. Lucia |             315|\n:::\n:::\n\nThe above table shows the top 5 spirit-consuming countries based on annual servings. Grenada is the top consumer with 438 servings per year (per capita), 65 servings more than Belarus in second place. Three of these countries are Caribbean, and the other two are Belarus and Russia. Vodka is culturally significant and very popular in both Russia and Belarus, so it is fitting to see them in the top 5 of spirit consumption. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(purealc_df,\n      caption = \"Top 5 Countries: Pure Alcohol Consumption\",\n      col.names = c(\"Country\", \"Pure Alcohol (litres)\"))\n```\n\n::: {.cell-output-display}\nTable: Top 5 Countries: Pure Alcohol Consumption\n\n|Country        | Pure Alcohol (litres)|\n|:--------------|---------------------:|\n|Belarus        |                  14.4|\n|Lithuania      |                  12.9|\n|Andorra        |                  12.4|\n|Grenada        |                  11.9|\n|Czech Republic |                  11.8|\n:::\n:::\n\nThe above table shows the top 5 pure alcohol-consuming countries based on total litres. Belarus is the top consumer with 14.4 litres per year (per capita). In 2010, Belarus consumed 17.5 litres of pure alcohol per capita. Although their consumption has decreased, they still remain the top consumer in this particular year.\n\n### Conclusion:\nI was eager to analyze this data and I'm content with what I found. Given that this data covers only 1 year, you can't look at certain trends; for example, wine consumption in France over a 10 year span. Also, there are some missing values or zero values which can provide some inaccuracy. I would like to look at data similar to this with a larger time horizon, which would allow for more in-depth analysis. \n\n### Connection to class: \nThe world map visualization is effective because I'm working with a \"global\" data set. It's interesting to look at quantitative variables on a world map, especially with a sequential color scale (when it's appropriate). As soon as I found this data set, I thought of the map example we did in class with \"well-being\" mapped globally. However, for looking at the top 5 consuming countries of the different types of alcohol, I believe a simple table is more appropriate. In this case, even a table works more effectively than a bar chart or similar visualization. \n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}